simplify installer

diff --git a/gpli b/gpli
--- a/gpli
+++ b/gpli
@@ -41,8 +41,9 @@
 #   - uninstall doesn't uninstall but nukes the wine prefix
 #   - switch: --info, display installation details
 
-# this script version
+# Meta
 VERSION=0.0.1
+_filename=$(basename $0)
 
 GPL_HOME=$HOME/.local/share/grand-prix-legends
 CACHE="$HOME/.cache/grand-prix-legends"
@@ -68,7 +69,7 @@ ISO_DEVICE="/dev/disk/by-label/GPL"
 WINE="$(which wine)"
 WINEPREFIX="$GPL_HOME/pfx"
 DRIVE_C="$WINEPREFIX/drive_c"
-_filename=$(basename $0)
+WIN_VERSION="win7"
 # use find?
 GPL_EXE="$WINEPREFIX/drive_c/Sierra/GPL/gpl.exe"
 GEM_EXE="$WINEPREFIX/drive_c/GPLSecrets/GEM+/GEMP2.exe"
@@ -402,27 +403,25 @@ get() {
 # Usage:
 #   Install [options] [...selection]
 # Opts:
-#   -r  'REINSTALL'
-# ex: 'install # gpl'
-# ex: 'install gpl # default'
-# ex: 'install -r gpl' "REINSTALL gpl"
-# ex: 'install gpl gem gplsecrets vbr'
+#   -y 'yes' accepts all options , not implemented
+# Example
+#  'install # gpl'
+#  'install gpl gem gplsecrets vbr'
 #
 Install() {
-    local REINSTALL=0
-    while getopts ":r" arg; do
+    local YES=0
+    while getopts ":f" arg; do
         case ${arg} in
-        r)
-            REINSTALL=1
+        y)
+            YES=1
             debug "Set to reinstall"
             ;;
         *)
-            error "unknown option '$OPTARG'"
+            error "Unknown option '$OPTARG'"
             return 1
             ;;
         esac
     done
-    local SELECTED=''
     if [[ $# -lt 1 ]]; then
         error "Expected args"
         return 1
@@ -431,164 +430,96 @@ Install() {
             case "$a" in
             -*) ;; # skip options
             gpl)
-                debug "GPL selected"
-                SELECTED+=" gpl "
+                # get GPL ISO installer, download if not in cache
+                if ! get "$ISO" "$ISO_URL" "$ISO_MD5" "$ISO_SHASUM"; then
+                    return 1
+                fi
+                # get GPL installer, download if not in cache
+                if ! get "$INSTALLER" "$INSTALLER_URL" "$INSTALLER_MD5" "$INSTALLER_SHASUM"; then
+                    return 1
+                fi
+                # try mount ISO, required by GPL installer
+                local mounted=0
+                if tryMount; then
+                    mounted=1
+                fi
+                #  GPL installer needs the CD
+                if [[ $mounted -eq 1 ]]; then
+                    debug "Running GPL installer"
+                    if runExe "$INSTALLER"; then
+                        GPL_INSTALLED=1
+                        debug "installed GPL"
+                    else
+                        error "Failed to install GPL"
+                    fi
+                else
+                    error "Can't install GPL"
+                fi
+                # try Unmount ISO
+                tryUnmount
                 ;;
             gem)
-                debug "GEM selected"
-                SELECTED+=" gem "
-                ;;
-            gplsecrets)
-                debug "gplsecrets selected"
-                SELECTED+=" gplsecrets "
-                ;;
-            vbr)
-                debug "VBR selected"
-                SELECTED+=" vbr "
-                ;;
-            *)
-                error "Can't install '$a'"
-                exit 1
-                ;;
-            esac
-        done
-    fi
-    debug "Args: $@"
-    if [ -z "$SELECTED" ]; then
-        error "Nothing to selected"
-        return 1
-    fi
-
-    local GPL_INSTALLED=0
-    if [ -f $GPL_EXE ]; then
-        debug "$(basename $GPL_EXE) found at $(dirname $GPL_EXE)"
-        GPL_INSTALLED=1
-    fi
-
-    # GPL
-    if [[ "$SELECTED" =~ " gpl " ]]; then
-        debug "Installing GPL"
-        # if not installed or reinstall
-        if [[ $GPL_INSTALLED -eq 0 || $REINSTALL -eq 1 ]]; then
-            # get GPL ISO installer, download if not in cache
-            if ! get "$ISO" "$ISO_URL" "$ISO_MD5" "$ISO_SHASUM"; then
-                return 1
-            fi
-            # get GPL installer, download if not in cache
-            if ! get "$INSTALLER" "$INSTALLER_URL" "$INSTALLER_MD5" "$INSTALLER_SHASUM"; then
-                return 1
-            fi
-            # try mount ISO, required by GPL installer
-            local mounted=0
-            if tryMount; then
-                mounted=1
-            fi
-            #  GPL installer needs the CD
-            if [[ $mounted -eq 1 ]]; then
-                debug "Running GPL installer"
-                if WineRunExe "$INSTALLER"; then
-                    GPL_INSTALLED=1
-                    debug "installed GPL"
-                else
-                    error "Failed to install GPL"
-                fi
-            else
-                error "Can't install GPL"
-            fi
-            # tryUnmount ISO
-            tryUnmount
-        else
-            info "GPL Installed"
-        fi
-    else
-        debug "GPL not in selection '$SELECTED'"
-    fi
-
-    # installing GEM
-    local GEM_INSTALLED=0
-    if [ -f $GEM_EXE ]; then
-        debug "$(basename $GEM) found at $(dirname $GEM)"
-        GEM_INSTALLED=1
-    fi
-    # GEM
-    if [[ "$SELECTED" =~ " gem " ]]; then
-        debug "installing GEM"
-        if [[ $GPL_INSTALLED -eq 1 ]]; then
-            # can't install GEM if there is no 'c:\Sierra\GPL\gpl.exe'
-            if [[ "$GEM_INSTALLED" -eq 0 || $REINSTALL -eq 1 ]]; then
+                debug "installing GEM"
                 # get GEM installer  download if not in cache
                 if get "$GEM" "$GEM_URL" "$GEM_MD5" "$GEM_SHASUM"; then
                     debug "Runnig GEM installer"
-                    if WineRunExe "$GEM"; then
+                    if runExe "$GEM"; then
                         GEM_INSTALLED=1
                         debug "installed GEM?"
                     else
                         debug "failed to install GEM"
                     fi
                 fi
-            else
-                info "GEM installed"
-            fi
-        else
-            error "Can't install GEM"
-        fi
-    else
-        debug "GEM+ not in selection '$SELECTED'"
-    fi
-    # Unpack GEM: into drive c:\
-    # prefix breaks when installing GEM+ with the installer
-    # try unpack required files
-    # WARN: 'GPLPatchDLL.dll must be included and extracted into syswow64?'
-    # and the VB runtime after!
-    if [[ "$SELECTED" =~ " gplsecrets " ]]; then
-        # get GEM installer  download if not in cache
-        if get "$GEM" "$GEM_URL" "$GEM_MD5" "$GEM_SHASUM"; then
-            local GPLSecrets="$DRIVE_C/GPLSecrets"
-            if [ ! -d "$DRIVE_C" ]; then
-                if ! createPrefix; then
-                    debug "Failed to create prefix: $WINEPREFIX"
-                    return 1
-                fi
-            fi
-            if ! innoextract "$GEM" -d "$DRIVE_C/gplsecrets" -s; then
-                error "failed to 'innoextract' '$(basename $GPLSecrets)'"
-            else
-                info "innoextracted '$(basenameNoExtension $GEM)' into '$GPLSecrets'"
-                if ! cp "$DRIVE_C/gplsecrets/syswow64/GPLPatchDLL.dll" "$DRIVE_C/windows/syswow64/"; then
-                    warn "Failed to copy GPLPatchDLL.dll to windows/syswow64"
-                    warn "GEMP2.exe might not work"
-                fi
-            fi
-        fi
-    else
-        debug "gplsecrets not in selection '$SELECTED'"
-    fi
-    # VBR
-    VB_RUNTIME_INSTALLED=0
-    # TODO if VB_RUNTIME_INSTALLED -eq 1
-    if [[ "$SELECTED" =~ "vbr" ]]; then
-        debug "Installig VBR"
-        if [[ $VB_RUNTIME_INSTALLED -eq 0 || $REINSTALL -eq 1 ]]; then
-            # if [[ $GEM_INSTALLED -eq 1 ]]; then
-            # fi
-            if get "$VB_RUNTIME_ZIP" "$VB_RUNTIME_URL"; then
-                if Unzip "$VB_RUNTIME_ZIP" "$CACHE"; then
-                    # unzipped to cache
-                    debug "Running VB Runtime Installer"
-                    if WineRunExe "$VB_RUNTIME_EXE"; then
-                        VB_RUNTIME_INSTALLED=1
-                        info "VB Runtime Installed"
-                    else
-                        error "Can't install VB Runtime"
+                ;;
+            gplsecrets)
+                # Unpack GEM: into drive c:\
+                # prefix breaks when installing GEM+ with the installer
+                # try unpack required files
+                # WARN: 'GPLPatchDLL.dll must be included and extracted into syswow64?'
+                # and the VB runtime after!
+                if get "$GEM" "$GEM_URL" "$GEM_MD5" "$GEM_SHASUM"; then
+                    # get GEM installer  download if not in cache
+                    local GPLSecrets="$DRIVE_C/GPLSecrets"
+                    if [ ! -d "$DRIVE_C" ]; then
+                        if ! createPrefix; then
+                            debug "Failed to create prefix: $WINEPREFIX"
+                            return 1
+                        fi
                     fi
-                else
-                    debug "can't unzip 'VB Runtime'"
+                    if ! innoextract "$GEM" -d "$DRIVE_C/gplsecrets" -s; then
+                        error "failed to 'innoextract' '$(basename $GPLSecrets)'"
+                    else
+                        info "innoextracted '$(basenameNoExtension $GEM)' into '$GPLSecrets'"
+                        if ! cp "$DRIVE_C/gplsecrets/syswow64/GPLPatchDLL.dll" "$DRIVE_C/windows/syswow64/"; then
+                            warn "Failed to copy GPLPatchDLL.dll to windows/syswow64"
+                            warn "GEMP2.exe might not work"
+                        fi
+                    fi
                 fi
-            fi
-        fi
-    else
-        debug "VBR not in selection '$SELECTED'"
-    fi
+                ;;
+            vbr)
+                if get "$VB_RUNTIME_ZIP" "$VB_RUNTIME_URL"; then
+                    if Unzip "$VB_RUNTIME_ZIP" "$CACHE"; then
+                        # unzipped to cache
+                        debug "Running VB Runtime Installer"
+                        if runExe "$VB_RUNTIME_EXE"; then
+                            VB_RUNTIME_INSTALLED=1
+                            info "VB Runtime Installed"
+                        else
+                            error "Can't install VB Runtime"
+                        fi
+                    else
+                        debug "can't unzip 'VB Runtime'"
+                    fi
+                fi
+                ;;
+            *)
+                error "Don't know how to install '$a'"
+                exit 1
+                ;;
+            esac
+        done
+    fi   
 }
 #
 # Args:
@@ -610,10 +541,11 @@ Unzip() {
 basenameNoExtension() {
     echo $(basename "$1") | tr -d "$2"
 }
-
-WIN_VERSION="win7"
+#
+#
+#
 createPrefix() {
-    if ! withPrefix wine winecfg -v "$WIN_VERSION"; then
+    if ! runWithPrefix wine winecfg -v "$WIN_VERSION"; then
         return 1
     else
         debug "Created prefix as '$WIN_VERSION'"
@@ -624,7 +556,7 @@ createPrefix() {
 # Args:
 #   $1 file
 #
-WineRunExe() {
+runExe() {
     if [ ! -f "$WINE" ]; then
         error "can't find wine, get wine on the \$PATH and try again"
         return 1
@@ -636,7 +568,7 @@ WineRunExe() {
 #
 # Run cmd on WINEPREFIX env
 #
-withPrefix() {
+runWithPrefix() {
     if [ ! -f "$WINE" ]; then
         error "can't find wine, get wine on the \$PATH and try again"
         return 1
@@ -656,11 +588,8 @@ remove() {
     read -p "Cannot be undone (y/n)? " u
     case $u in
     y)
-        if rm -rf "$2"; then
-            return 0
-        else
-            return 1
-        fi
+        rm -rf "$2"
+        return $?
         ;;
     n)
         info "Cancelled."
@@ -723,15 +652,15 @@ Open() {
 Launch() {
     case "$1" in
     gpl)
-        withPrefix "$WINE" 'c:\sierra\GPL\gpl.exe'
+        runWithPrefix "$WINE" start 'c:\sierra\GPL\gpl.exe' /d 'c:\sierra\GPL'
         ;;
     gpl67)
-        withPrefix "$WINE" 'c:\sierra\GPL\gplc67.exe'
+        runWithPrefix "$WINE" 'c:\sierra\GPL\gplc67.exe' /d 'c:\sierra\GPL'
         ;;
     gem+)
         # TODO: use find -> winepath ?
-        if ! withPrefix "$WINE" 'c:\GPLSecrets\GEM+\GEMP2.exe'; then
-            if ! withPrefix "$WINE" 'c:\gplsecrets\app\GEM+\GEMP2.exe'; then
+        if ! runWithPrefix "$WINE" 'c:\GPLSecrets\GEM+\GEMP2.exe' /d 'c:\sierra\GPL'; then
+            if ! runWithPrefix "$WINE" 'c:\gplsecrets\app\GEM+\GEMP2.exe'; then
                 error "Can't find or open GEMP2.exe"
             fi
         fi
@@ -764,9 +693,9 @@ usage() {
     echo "Verbs: "
     echo "  install [options?] [what]?   'run GPL installers'"
     echo "      options:"
-    echo "          -r  'REINSTALL'"
+    echo "          no options implemented"
     echo "      what:"
-    echo "         values: gpl gem vbr"
+    echo "         values: gpl gem vbr gplsecrets"
     echo "      example:"
     echo "          \$gpli install -r gpl # REINSTALL gpl"
     echo "          \$gpli install -r gpl gem vbr # reinstall gpl gem vbr"
@@ -903,11 +832,11 @@ uninstall)
     ;;
 run)
     shift
-    withPrefix $@
+    runWithPrefix $@
     ;;
 wine)
     shift
-    withPrefix "$WINE" $@
+    runWithPrefix "$WINE" $@
     ;;
 open)
     shift
