break installer into sub proc with options

diff --git a/gplnx b/gplnx
--- a/gplnx
+++ b/gplnx
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# Grand Prix Legends Linux 
-# ## Desc: 
+# Grand Prix Legends Linux
+# ## Desc:
 #   Creates wine prefix, mounts iso, downloads and runs the GPL, GEM+ and  Visual Basic runtime installers
 # ## Works on:
 #   - Ubuntu
@@ -411,6 +411,137 @@ get() {
     fi
 }
 #
+# Installs GEM+
+# Args:
+#   none
+# Options:
+#   -i  Use/run the installer
+#   -u  Unpack the installer
+#   -h  show usage
+#
+install:gem() {
+    # show usage
+    install:gem:usage() {
+        echo "Installs GEM+"
+        echo "$_filename install gem [options] [args]"
+        echo "Options: "
+        echo " -i Runs GEM+ installer"
+        echo " -u Unpacks GEM+ installer"
+        echo " -h Shows this"
+    }
+    while getopts ":iuh" arg; do
+        case ${arg} in
+        i)
+            debug "Running GEM+ installer"
+            # get GEM installer  download if not in cache
+            if get "$GEM_PACKAGE_EXE" "$GEM_PACKAGE_URL" "$GEM_PACKAGE_EXE_SHA"; then
+                debug "Runnig GEM+ installer"
+                if runExe "$GEM_PACKAGE_EXE"; then
+                    GEM_INSTALLED=1
+                    debug "installed GEM+?"
+                else
+                    debug "failed to install GEM+"
+                fi
+            fi
+            ;;
+        u)
+            # Unpack GEM+ into drive c:\
+            # prefix breaks when installing GEM+ with the installer
+            if get "$GEM_PACKAGE_EXE" "$GEM_PACKAGE_URL" "$GEM_PACKAGE_EXE_SHA"; then
+                # get GEM+ installer  download if not in cache
+                if [ ! -d "$DRIVE_C" ]; then
+                    if ! createPrefix; then
+                        debug "Failed to create prefix: $WINEPREFIX"
+                        return 1
+                    fi
+                fi
+                if [ -z "$(which innoextract)" ]; then
+                    error "Can't find 'innoextract', install innoextract and try again"
+                    return 1
+
+                fi
+                local GPLSecrets="$DRIVE_C/GPLSecrets"               
+                if ! innoextract "$GEM_PACKAGE_EXE" -d "$GPLSecrets" -s; then
+                    error "failed to extract '$GEM_PACKAGE_EXE'"
+                    return 1
+                fi
+                debug "extracted $GEM_PACKAGE_EXE into '$GPLSecrets'"             
+                if ! cp "$GPLSecrets/syswow64/GPLPatchDLL.dll" "$DRIVE_C/windows/syswow64/"; then
+                    warn "Failed to move GPLPatchDLL.dll to windows/syswow64"
+                    warn "GEMP2.exe might not work"
+                fi
+                info "Extracted $GEM_PACKAGE_EXE into $GPLSecrets"
+            fi
+            ;;
+        h)
+            install:gem:usage
+            ;;
+        *)
+            error "Unknown option '$OPTARG'"
+            return 1
+            ;;
+        esac
+    done
+    if [[ $# -lt 1 ]]; then
+        error "Expected options"
+        install:gem:usage
+        return 1
+    fi
+}
+#
+# Install GPL
+#
+install:gpl() {
+    # get GPL ISO installer, download if not in cache
+    if ! get "$GPL_ISO" "$GPL_ISO_URL" "$GPL_ISO_SHA"; then
+        return 1
+    fi
+    # get GPL installer, download if not in cache
+    if ! get "$GPL_INSTALLER_EXE" "$GPL_INSTALLER_URL" "$GPL_INSTALLER_EXE_SHASUM"; then
+        return 1
+    fi
+    # try mount ISO, required by GPL installer
+    local mounted=0
+    if Mount:try "$GPL_ISO" "$GPL_ISO_LABEL" "$GPL_ISO_MNT_POINT" "$WSLDRIVE"; then
+        mounted=1
+    fi
+    #  GPL installer needs the CD
+    if [[ $mounted -eq 1 ]]; then
+        debug "Running GPL installer"
+        if runExe "$GPL_INSTALLER_EXE"; then
+            GPL_INSTALLED=1
+            debug "installed GPL"
+        else
+            error "Failed to install GPL"
+        fi
+    else
+        error "Can't install GPL"
+    fi
+    # try Unmount ISO
+    if ! Unmount:try "$GPL_ISO" "$GPL_ISO_LABEL" "$GPL_ISO_MNT_POINT"; then
+        error "Failed to unmount "$GPL_ISO_LABEL" "$GPL_ISO""
+    fi
+}
+#
+# Install Visual Basic Runtime
+#
+install:vbr() {
+    if get "$VB_RUNTIME_ZIP" "$VB_RUNTIME_URL" "$VB_RUNTIME_ZIP_SHA"; then
+        if Unzip "$VB_RUNTIME_ZIP" "$CACHE"; then
+            # unzipped to cache
+            debug "Running VB Runtime Installer"
+            if runExe "$VB_RUNTIME_EXE"; then
+                VB_RUNTIME_INSTALLED=1
+                info "VB Runtime Installed"
+            else
+                error "Can't install VB Runtime"
+            fi
+        else
+            debug "can't unzip 'VB Runtime'"
+        fi
+    fi
+}
+#
 # Install
 # Usage:
 #   Install [options] [...selection]
@@ -422,11 +553,12 @@ get() {
 #
 Install() {
     local YES=0
-    while getopts ":f" arg; do
+    while getopts ":h" arg; do
         case ${arg} in
-        y)
-            YES=1
-            debug "Set to reinstall"
+        h)
+            echo "install [options] [target]"
+            echo "Options: -h shows this"
+            echo "Targets: gpl gem vbr"
             ;;
         *)
             error "Unknown option '$OPTARG'"
@@ -442,96 +574,16 @@ Install() {
             case "$a" in
             -*) ;; # skip options
             gpl)
-                # get GPL ISO installer, download if not in cache
-                if ! get "$GPL_ISO" "$GPL_ISO_URL" "$GPL_ISO_SHA"; then
-                    return 1
-                fi
-                # get GPL installer, download if not in cache
-                if ! get "$GPL_INSTALLER_EXE" "$GPL_INSTALLER_URL" "$GPL_INSTALLER_EXE_SHASUM"; then
-                    return 1
-                fi
-                # try mount ISO, required by GPL installer
-                local mounted=0
-                if Mount:try "$GPL_ISO" "$GPL_ISO_LABEL" "$GPL_ISO_MNT_POINT" "$WSLDRIVE"; then
-                    mounted=1
-                fi
-                #  GPL installer needs the CD
-                if [[ $mounted -eq 1 ]]; then
-                    debug "Running GPL installer"
-                    if runExe "$GPL_INSTALLER_EXE"; then
-                        GPL_INSTALLED=1
-                        debug "installed GPL"
-                    else
-                        error "Failed to install GPL"
-                    fi
-                else
-                    error "Can't install GPL"
-                fi
-                # try Unmount ISO
-                if ! Unmount:try "$GPL_ISO" "$GPL_ISO_LABEL" "$GPL_ISO_MNT_POINT"; then
-                    error "Failed to unmount "$GPL_ISO_LABEL" "$GPL_ISO""
-                fi
+                shift
+                install:gpl $@
                 ;;
             gem)
-                debug "installing GEM"
-                # get GEM installer  download if not in cache
-                if get "$GEM_PACKAGE_EXE" "$GEM_PACKAGE_URL" "$GEM_PACKAGE_EXE_SHA"; then
-                    debug "Runnig GEM installer"
-                    if runExe "$GEM_PACKAGE_EXE"; then
-                        GEM_INSTALLED=1
-                        debug "installed GEM+?"
-                    else
-                        debug "failed to install GEM+"
-                    fi
-                fi
-                ;;
-            gplsecrets)
-                # Unpack GEM+ into drive c:\
-                # prefix breaks when installing GEM+ with the installer
-                if get "$GEM_PACKAGE_EXE" "$GEM_PACKAGE_URL" "$GEM_PACKAGE_EXE_SHA"; then
-                    # get GEM+ installer  download if not in cache
-                    if [ ! -d "$DRIVE_C" ]; then
-                        if ! createPrefix; then
-                            debug "Failed to create prefix: $WINEPREFIX"
-                            return 1
-                        fi
-                    fi
-                    if [ -z "$(which innoextract)" ]; then
-                        error "Can't find 'innoextract', install innoextract and try again"
-                    else
-                        local GPLSecrets="$DRIVE_C/GPLSecrets"
-                        #
-                        # if [ -d $GPLSecrets ] return 1
-                        # mkdir $DRIVE_C/temp && innoextract "$GEM_PACKAGE_EXE" -d "$DRIVE_C/temp/gplsecrets" -s
-                        #   && mv "$DRIVE_C/temp/gplsecrets/app"  "$GPLSecrets"
-                        #
-                        if ! innoextract "$GEM_PACKAGE_EXE" -d "$DRIVE_C/gplsecrets" -s; then
-                            error "failed to extract '$(basename $GPLSecrets)'"
-                        else
-                            info "extracted '$(basenameNoExtension $GEM_PACKAGE_EXE)' into '$GPLSecrets'"
-                            if ! cp "$DRIVE_C/gplsecrets/syswow64/GPLPatchDLL.dll" "$DRIVE_C/windows/syswow64/"; then
-                                warn "Failed to copy GPLPatchDLL.dll to windows/syswow64"
-                                warn "GEMP2.exe might not work"
-                            fi
-                        fi
-                    fi
-                fi
+                shift
+                install:gem $@
                 ;;
             vbr)
-                if get "$VB_RUNTIME_ZIP" "$VB_RUNTIME_URL" "$VB_RUNTIME_ZIP_SHA"; then
-                    if Unzip "$VB_RUNTIME_ZIP" "$CACHE"; then
-                        # unzipped to cache
-                        debug "Running VB Runtime Installer"
-                        if runExe "$VB_RUNTIME_EXE"; then
-                            VB_RUNTIME_INSTALLED=1
-                            info "VB Runtime Installed"
-                        else
-                            error "Can't install VB Runtime"
-                        fi
-                    else
-                        debug "can't unzip 'VB Runtime'"
-                    fi
-                fi
+                shift
+                install:vbr $@
                 ;;
             *)
                 error "Don't know how to install '$a'"
@@ -717,11 +769,11 @@ usage() {
     echo "Grand Prix Legends wine Installer v$VERSION"
     echo "Usage: '$_filename [verb] [options]'"
     echo "Verbs: "
-    echo "  install [options?] [what]?   'run GPL installers'"
+    echo "  install [options?] [target]?   'run GPL installers'"
     echo "      options:"
-    echo "          no options implemented"
-    echo "      what:"
-    echo "         values: gpl gem vbr gplsecrets"
+    echo "          -h help"
+    echo "      target:"
+    echo "          gpl gem vbr"
     echo "      example:"
     echo "          \$gpli install -r gpl # REINSTALL gpl"
     echo "          \$gpli install -r gpl gem vbr # reinstall gpl gem vbr"
