wsl: open pfx/?

diff --git a/gplnx b/gplnx
--- a/gplnx
+++ b/gplnx
@@ -201,7 +201,7 @@ mount:udisksctl() {
 # Args:
 #   $1  'Drive Letter'
 #
-wsl:drive:valid() {    
+wsl:drive:valid() {
     if [ -z "$1" ]; then
         return 1 # failed
     fi
@@ -775,6 +775,87 @@ uninstall:selected() {
 
 }
 #
+#
+#
+pfx:path() {
+    debug "args=$@"
+    
+    # TODO: fix this, translate win path
+    if [ ! -z "$1" ]; then        
+        if [[ "$1" =~ ^[a-zA-Z]: ]]; then
+            # debug "is wine path"
+            local p="$(winepath "$1")"
+        else            
+            debug "Not wine path $1"
+            local p="$WINEPREFIX/$1"
+            if [ ! -e  "$p" ]; then
+                error "Can't find '$p'"
+                exit 1
+            fi
+        fi
+    fi
+    echo $p
+}
+#
+# open $WINEPREFIX/$1 in terminal
+# Args:
+#   $1  'path'
+#
+open:terminal() {
+    if ! p="$(pfx:path $1)"; then
+        return 1
+    fi
+    debug "opening '$p'"
+    case $OS in
+    $OS_DARWIN)
+        error "'$OS' '${FUNCNAME[0]}' Not implemented"
+        return 1
+        ;;
+    $OS_WSL)
+        if cd "$p"; then 
+            x-terminal-emulator & # --working-director
+        else 
+            return 1
+        fi
+        ;;
+    $OS_LINUX)
+        if cd "$p" ; then 
+            x-terminal-emulator "--working-directory=$PWD" & # doesn't always work
+        else 
+            return 1
+        fi
+        ;;
+    *)
+        error "'$OS' '${FUNCNAME[0]}' Not implemented"
+        return 1
+        ;;
+    esac
+}
+open:x() {
+    p="$(pfx:path $1)"
+    debug "opening '$p'"
+    case $OS in
+    $OS_DARWIN)
+        open p
+        return 1
+        ;;
+    $OS_LINUX)
+         if cd "$p"; then 
+          x-terminal-emulator "--working-directory=$PWD" & # doesn't always work
+         else
+            return 1
+         fi
+        ;;
+    $OS_WSL)
+        if cd "$p"; then 
+            xdg-open "$p" &
+        else
+            return 1
+        fi
+        ;;
+    esac
+}
+#
 # open WINEPREFIX/?
 # Args:
 #   $1? path
@@ -783,19 +864,25 @@ uninstall:selected() {
 #   -x open in terminal
 #
 open:pfx() {
-    local x=0
-    while getopts ':xh' arg; do
+    while getopts ':xth' arg; do
         case "$arg" in
         h)
             echo "$_filename open [options] [path]"
             echo "  options:"
             echo "      -h  'shows this'"
-            echo "      -x  'open in terminal'"
+            echo "      -t  'open in terminal'"
             return 0
+            ;;
+        t)
+            shift
+            echo "$@"
+            open:terminal "$@"
+            return $?            
             ;;
         x)
             shift
-            x=1
+            open:x "$@"
+            return $?
             ;;
         *)
             error "Unknown option '$arg'"
@@ -803,39 +890,7 @@ open:pfx() {
             ;;
         esac
     done
-    if [ ! -d "$WINEPREFIX" ]; then
-        error "Can't find '$WINEPREFIX'"
-        exit 1
-    fi
-
-    local p="$WINEPREFIX"
-       # TODO: fix this, translate win path    
-    if [ ! -z "$1" ] && [[ "$1" =~ ^[a-zA-Z]: ]]; then         
-        p=$(winepath "$1")
-        else
-        p+="/$1"
-    fi
-     
-    if [ ! -d "$p" ]; then
-        error "Can't find '$p'"
-        exit 1
-    fi
-
-    debug "opening '$p'"
-    if [ $OS == $OS_DARWIN ]; then
-        if [[ "$x" -eq 1 ]]; then
-            error "Not implemented"
-            return 1
-        else
-            open "$p"
-        fi
-    else
-        if [[ "$x" -eq 1 ]]; then
-            cd "$p" && x-terminal-emulator "--working-directory=$PWD" # doesn't work
-        else
-            xdg-open "$p"
-        fi
-    fi
+    open:x "$@"
 }
 #
 #
@@ -1032,7 +1087,7 @@ wine)
     ;;
 open)
     shift
-    open:pfx "$1"
+    open:pfx $@
     ;;
 launch)
     shift
